name: Update Translator Data
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run logic
        run: python app.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Auto-update dictionary" || exit 0
          git push
